language: node_js
node_js:
- 10.15.3
deploy:
  provider: heroku
  api_key:
    secure: b7ctUpPsTjTCluDIYQ6prNmVq5qq7jxFScFIBu2+al4M61fXOMJsrWS1qchdAsZ7CZFSKtByk49lu0/rlV3vEE7bam1wK9kY6+OWXvvhEE82VSpfuSMp3wKZVNUJF5t2eMM0tJD9rliMJqg/5OzJ9nXbvfx7r66PAtLYox8ZYNN6VNPeIQ3JTULFkf0cYyMUR0wxTqbdmVLqyjtCI33kuY+M8IOgXpus1Q/tW3nSY6kWw7eoEYY4V1hCZWzoYn+nrhNOATskhts/hTGsHes2aow8ZrUGBMt1LcgYugRphIhYTW4Ky6rqtAURLwDMoDLpbr/OnJc2ho1BfaZnyiXOm8tHypb8GgY24nJiotzSUT19xf50gz5bNYIG1l49hK66lsJI3+OLsh1Hi67SRFFYog6XQflI7/D3lkVb+bAS/dgGK5Myef+nIOrnkqw/BJILvVCPuunL4itpbXJDZM4zFeCaR3uxIpR91wjLCRK2uIP8emwXvIL3H+rirOgZTjswOX87ru1SatKeK6WCBtQNIAPOnk7xxq1XGkGm2wO8m9hJHOvYKGrT7l06cso/BpjVJAMeba5hi0CK/XDrsuhDjI73+3yXZ6XQ/+O9qGGGb2in3XZbQeHepGE+NnJgE2XrQTIs8Yy2kbl4oKp25HcjGxEVoXujtiz5kTOgLE++EWQ=
  app: books-api-nb
  on:
    repo: nipunbatra1804/books-api
notifications:
  slack: jumpstart-4:jwRFsWDpOlxuqHRcfR9UyhMi
